---
abstract: 'functions for various exact algebraic calculations'
author:
  - 'Alessandro Gorohovski <angel@feht.dgtu.donetsk.ua>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Assistant
no_index:
  directory:
    - t
    - inc
requires:
  Algorithm::Combinatorics: 0.27
  Carp: 0
  Math::BigFloat: 1.993
  Math::BigInt: 1.997
  Test::More: 0.98
version: 0.0417
